name: Deploy to GitHub Pages

on:
  # Dispara o deploy quando algo for comitado na branch 'main'
  push:
    branches: ["main"]
  # Permite rodar o workflow manualmente pela aba Actions do GitHub
  workflow_dispatch:

# Configura as permissões para permitir o deploy para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente por vez
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build (Construir o site)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
        
      - name: Build do projeto
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O Vite gera o site na pasta dist
          path: './dist'

  # Job de Deploy (Publicar no Pages)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
